# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'svcamcloud-mobile' do

pod 'RBStoryboardLink', '~> 0.1'
pod 'AFNetworking', '~> 2.5'

end

target 'svcamcloud-mobileTests' do

end

